### ISSUE TITLE
Às vezes a bolinha tá parada e não aparece para fazer o lançamento

### ISSUE THREAD

**Issue by csamuelsm** [c1c3ro/Golfing-Extreme#16]
Alguém tem ideia de por que?

**Comment by c1c3ro** [comment]
As vezes ela ta rodando só que BEM devagar, quase imperceptível, aí ele acaba não entrando na condição, acho que esse é o problema. Uma solução é fazer com que se a bolinha tiver numa velocidade bem baixa, bota a velocidade pra zero, pra ela parar logo. Eu tentei fazer isso mas deu um erro, então deixei quieto kkkkk
